spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:taskmanagement}
spring.datasource.username=${POSTGRES_USER:taskmanagement}
spring.datasource.password=${POSTGRES_PASSWORD:taskmanagement}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
